### ISSUE TITLE
Hi, Not an issue, I'm just curious about the project.

### ISSUE THREAD

**Issue by anooprh** [Plaristote/crails#1]
Hi, hope you are doing well. I just wanted to ask if do you mind if I try to make some contributions to the project. I have some experience in both rails and C++.

I also wanted to know the usefulness of this application. Do you use it in your company/any web sites which are running on this? Just curious.

**Comment by Plaristote** [comment]
Hi ! I'm alright with contributions on this project, there's plenty of feature that crails could use !

About the usefulness: it hasn't been used on any serious project yet. I've got some personal projects planned to use as showcases for crails, though I'm currently too busy on ruby and javascript stacks to finish them in the near future.

It's close to ready though: it's already pretty quick to work on REST APIs and MongoDB. But it definitely needs more testing (one of the missing feature is implementing/developping a unit testing framework), and it would also be wiser to wait for the cpp-netlib, on which crails is based, to reach their first stable version.

Thank you for your curiosity !
