### ISSUE TITLE
Any options of using Libuv ?

### ISSUE THREAD

**Issue by GuacheSuede** [Plaristote/crails#2]

**Comment by GuacheSuede** [comment]
@Plaristote

**Comment by Plaristote** [comment]
Sorry for the delay ! There's no such option, I'm afraid.
We use cpp-netlib, which itself uses boost.asio for all I/O related jobs.

Cpp-netlib is already asynchronous, and our implementation reflects that (responses are given through a call to an `std::function`, which can be called outside of the request's original thread).

Is there a particular reason why you would need to use Libuv ?

**Comment by GuacheSuede** [comment]
Sry for the delay, personal bechmarks have shown libuv to be much faster
